### ISSUE TITLE
[FEEDBACK] Add times from timer to history

### ISSUE THREAD

**Issue by heinrichreimer** [mbullington/interval-issues#6]
# User Feedback

When I start a timer, I would like the Option to stop it and automatically add the spent time to my history.

**Comment by mbullington** [comment]
Hi Heinrich,

The timer should automatically add to History every time it is paused, is this not the case for you? If not tha

Could you please provide device, Android version, etc?

**Comment by heinrichreimer** [comment]
It works as described 👍
